### ISSUE TITLE
[Feature Request] Adding several media folders to cross check

### ISSUE THREAD

**Issue by ltctceplrm** [garnajee/removarr#1]
I've just tried your program and it's ver handy, the only problem is that I've got one /storage/Downloads/ folder and then several folders like /storage/Movies/ and /storage/Series/, I'd like to be able to cross check in all the media folders if there are any non-hardlinked files.

**Comment by garnajee** [comment]
I've already been asking for this feature,  I'm working on it.
My idea is to add a condition on the number of volumes in the Dockerfile and add the value of the number of volumes in the docker-compose.yml.

Something like this:

* 1st docker-compose.yml
```yml
version: '3.9'
services:
  removarr:
    image: ghcr.io/garnajee/removarr:latest
    container_name: removarr
    restart: always
    environment:
      - PUID=1030
      - PGID=100
      - APP_VOLUMES_COUNT=2
    volumes:
      - '/tmp/test/completed/:/data/completed'
      - '/tmp/test/medias/:/data/medias'
    ports:
      - '127.0.0.1:8012:5000'
```

* 2nd docker-compose.yml
```yml
version: '3.9'
services:
  removarr:
    image: ghcr.io/garnajee/removarr:latest
    container_name: removarr
    restart: always
    environment:
      - PUID=1030
      - PGID=100
      - APP_VOLUMES_COUNT=3
    volumes:
      - '/tmp/test/completed/:/data/completed'
      - '/tmp/test/movies/:/data/movies'
      - '/tmp/test/series/:/data/series'
    ports:
      - '127.0.0.1:8012:5000'
```
And obviously, modify the python code.

If you have any other idea, I'm interested
